"""add week submissions table

Revision ID: 236e478e4f67
Revises: 8e14dad570d9
Create Date: 2026-09-21 15:22:09.761626

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "236e478e4f67"
down_revision: str | None = "8e14dad570d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "week_submissions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("week_id", sa.Uuid(), nullable=False),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["week_id"], ["nfl_weeks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "week_id", name="uq_week_submissions_user_week"),
    )
    op.create_index(
        op.f("ix_week_submissions_user_id"), "week_submissions", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_week_submissions_week_id"), "week_submissions", ["week_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_week_submissions_week_id"), table_name="week_submissions")
    op.drop_index(op.f("ix_week_submissions_user_id"), table_name="week_submissions")
    op.drop_table("week_submissions")
    # ### end Alembic commands ###
